### ISSUE TITLE
gposingway-update.bat just deletes everying in .\game folder upon install

### ISSUE THREAD

**Issue by ToxixThunda** [gposingway/gposingway#40] opened 2024-06-21 03:57 UTC
Well hello.
So as of a little bit ago I had attempted to install Gposingway, went through all of the install instructions provided before hand. But for some reason, your .bat deletes everything on the game directory. And I mean everything the whole entire directory is wiped. I took a look at the .bat, and it seems that in the deprecated items section it is set up to wipe the game directory clean. why?

```

:deprecated-cleanup

:: Deprecated items
echo.
echo Doing some clean-up...
if not exist "%TEMP_DIR%\gposingway-definitions.json" exit /b 1
for /f "delims=" %%a in ('powershell -command "Get-Content '%TEMP_DIR%\gposingway-definitions.json' | ConvertFrom-Json | Select-Object -ExpandProperty Deprecated"') do (
    for %%b in (%%a) do (

        rmdir /s /q "%GAME_DIR%%%~b" 2>nul
        del /q /f "%GAME_DIR%%%~b" 2>nul
    )
)
```

**Comment by LeonAquitaine** [comment] 2024-06-21 13:29
Thanks for bringing iot to my attention. This is certainly an unwanted behavior; that block is intended to remove deprecated files, like incompatible shaders or collections.

A guardrail was added through this commit, and It's under test right now:

https://github.com/gposingway/gposingway/commit/1e4fd27f55d40b3aae326dd0c107f2b8273d2341

**Comment by LeonAquitaine** [comment] 2024-06-22 01:19
While the issue couldn't be reproduced, knowing about the exact point of failure (the module that deals with deprecated files and folders) helped to identify possible causes. Path checks were added for redundancy and safeguard, so data loss shouldn't be an issue anymore.

I'll keep testing, but in the meantime I'll close this issue.

**Closed** 2024-06-22 01:19 UTC
Labels: bug
